version: "3.9"
services:
  backend:
    build: 
      context: .
      dockerfile: backend/app/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app/backend
      - ./tictactoe.db:/app/tictactoe.db
    environment:
      - FLASK_ENV=production

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:8080"
    volumes:
    - ./frontend:/app
    - /app/node_modules
    depends_on:
      - backend
